name: Cleanup PR Tags and Adtifacts

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CleanUp Nugets
        run: |

          PACKAGES=$(curl -s -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }} "https://api.github.com/orgs/${{ github.repository.owner }}/packages?package_type=nuget" | jq -r '.[].name')

          for PACKAGE in $PACKAGES; do
            echo "Deleting package: $PACKAGE"
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }} "https://api.github.com/orgs/${{ github.repository.owner }}/packages/nuget/$PACKAGE/versions" -s -o /dev/null
          done

      - name: CleanUp Tags
        run: |

          TAGS= $(git tag -l "v*.*.alpha-${{ github.event.pull_request.number }}")
          for TAG in TAGS; do
            echo "Deleting tag: $TAG"
            git push origin :refs/tags/$TAG
          done
