name: Cleanup PR Tags and Adtifacts

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CleanUp Nugets
        run: |

          PACKAGES=$(curl -s -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/versions" | jq -r '.[].name')
          echo "${{ github.repository_owner }}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.run_id }}"

          for PACKAGE in $PACKAGES; do
            echo "Working on package: $PACKAGE"
            if [[ $PACKAGE == *"-alpha-${{ github.event.pull_request.number }}."* ]]; then
              echo "A borrar --> $PACKAGE"
              # curl -X DELETE -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PACKAGE/versions" -s -o /dev/null
            else
              echo "A conserar --> $PACKAGE"
            fi
          done

      - name: CleanUp Tags
        run: |

          TAGS= $(git tag -l "v*.*.alpha-${{ github.event.pull_request.number }}")
          for TAG in TAGS; do
            echo "Deleting tag: $TAG"
            git push origin :refs/tags/$TAG
          done
