name: Cleanup PR Tags and Adtifacts

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CleanUp Nugets
        run: |

          echo "${{ github.repository_owner }}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.repository }}"
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "Projecte: $PROJECT"
          URL="https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PROJECT/versions"
          echo "$URL"

          PACKAGES=$(curl -s -L -H "X-GitHub-Api-Version: 2022-11-28"  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" $URL | jq -c '.[]')

          for PACKAGE in $PACKAGES; do
            VERSION_NAME=$(echo "$PACKAGE" | jq -r '.name')
            VERSION_ID=$(echo "$PACKAGE" | jq -r '.id')
            if [[ $VERSION_NAME == *"-alpha-${{ github.event.pull_request.number }}."* ]]; then
              echo "A borrar --> $VERSION_NAME with $VERSION_ID ID"
              DELETE_URL="$URL/$VERSION_ID"
              echo "$DELETE_URL"
              curl -s -X DELETE "X-GitHub-Api-Version: 2022-11-28"  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "$DELETE_URL"
            else
              echo "A conserar --> $VERSION_NAME"
            fi
          done

      - name: CleanUp Tags
        run: |
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          URL="https://api.github.com/repos/${{ github.repository_owner }}/$PROJECT/git/refs/tags"
          git fetch --tags
          TAGS=$(git tag -l "*-alpha-${{ github.event.pull_request.number }}.*")
          for TAG in $TAGS; do
            echo "Deleting tag: $TAG"
            DELETE_URL="$URL/$TAG"
            echo "$DELETE_URL"
            curl -s -X DELETE "X-GitHub-Api-Version: 2022-11-28"  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "$DELETE_URL"
          done
