name: Cleanup PR Tags and Adtifacts

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CleanUp Nugets
        run: |

          echo "${{ github.repository_owner }}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.repository }}"
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "Projecte: $PROJECT"
          URL="https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PROJECT/versions"
          echo "$URL"

          PACKAGES=$(curl -L -H "X-GitHub-Api-Version: 2022-11-28"  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" $URL | jq -r '.[].name')

          for PACKAGE in $PACKAGES; do
            echo "Working on package: $PACKAGE"
            if [[ $PACKAGE == *"-alpha-${{ github.event.pull_request.number }}."* ]]; then
              echo "A borrar --> $PACKAGE"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PROJECT/$PACKAGE" -s -o /dev/null
            else
              echo "A conserar --> $PACKAGE"
            fi
          done

      - name: CleanUp Tags
        run: |
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          git remote set-url origin https://${{ secrets.NUGET_TOKEN }}@github.comn/${{ github.repository_owner }}/$PROJECT
          git fetch --tags
          TAGS=$(git tag -l "*-alpha-${{ github.event.pull_request.number }}.*")
          for TAG in TAGS; do
            echo "Deleting tag: $TAG"
            # git push origin --delete $TAG
          done
