name: Build and Deploy Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, dev]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: echo "Building for dev environment"
    - name: Show IP
      run: ip a
