name: Publish NuGet

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

    branches:
      - main
      - release
    tags:
      - 'v[0-9]*.[0-9]*.0'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Build and Publish
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # GitVersion setup
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'
      - name: Run GitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
          configFilePath: ./GitVersion.yml
          versionSpec: '6.0.x'
      - name: Show git version
        run: |
          echo "Version --> ${{ steps.gitversion.outputs.SemVer }}"

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.SemVer }} --no-build --output ./nupkg
      - name: Publish
        run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/Thiguish/index.json --api-key ${{ secrets.NUGET_TOKEN }}


      - name: Check if the tag already exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ steps.gitversion.outputs.SemVer }}")
          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV

      - name: Increment version and tag
        if: env.TAG_EXISTS == ''
        run: |
          VERSION=${{ steps.gitversion.outputs.SemVer }}
          echo "New version: $VERSION"

          # Crea un tag con la nueva versión
          git tag "v$VERSION"
          git push origin "v$VERSION"
