name: Publish NuGet

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    
    branches:
      - main
    tags:
      - 'v[0-9]*.[0-9]*.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Build and Publish
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # GitVersion setup
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'
      - name: Run GitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
          configFilePath: ./GitVersion.yml
          versionSpec: '6.0.x'
      - name: Show git version
        run: |
          echo "Version --> ${{ steps.gitversion.outputs.SemVer }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.event.pull_request.number }}"
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "Projecte: $PROJECT"

      - name: CleanUp Nugets
        run: |

          echo "${{ github.repository_owner }}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.repository }}"
          PROJECT=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "Projecte: $PROJECT"
          URL="https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PROJECT/versions"
          echo "$URL"

          PACKAGES=$(curl -L -H "X-GitHub-Api-Version: 2022-11-28"  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" $URL | jq -r '.[].name')

          for PACKAGE in $PACKAGES; do
            echo "Working on package: $PACKAGE"
            if [[ $PACKAGE == *"-alpha-${{ github.event.pull_request.number }}."* ]]; then
              echo "A borrar --> $PACKAGE"
              # curl -X DELETE -H "Authorization: Bearer ${{ secrets.NUGET_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/nuget/$PROJECT/$PACKAGE" -s -o /dev/null
            else
              echo "A conserar --> $PACKAGE"
            fi
          done

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.SemVer }} --no-build --output ./nupkg
      - name: Publish
        run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/Thiguish/index.json --api-key ${{ secrets.NUGET_TOKEN }}


      - name: Check if the tag already exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ steps.gitversion.outputs.SemVer }}")
          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV

      - name: Increment version and tag
        if: env.TAG_EXISTS == ''
        run: |
          VERSION=${{ steps.gitversion.outputs.SemVer }}
          echo "New version: $VERSION"

          # Crea un tag con la nueva versión
          git tag "v$VERSION"
          git push origin "v$VERSION"
